---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ngrok-agent-sa
  namespace: ngrok-agent
--- 
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ngrok-agent-cr
rules:
  - apiGroups: [""]
    resources: ["secrets","configmaps"]
    verbs: ["get", "list", "watch","create","update","delete"]
--- 
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ngrok-agent-crb
subjects:
  - kind: ServiceAccount
    name: ngrok-agent-sa
    namespace: ngrok-agent
roleRef:
  kind: ClusterRole
  name: ngrok-agent-cr
  apiGroup: rbac.authorization.k8s.io
---  